/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * My API Documentation - version v1
 *
 * API documentation with Hono and OpenAPI
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.get_api_users_list': ['GET', '/api/users/list'],
  'general.get_api_users_id': ['GET', '/api/users/{id}'],
  'general.post_api_users': ['POST', '/api/users']
};
